spring.application.name=billing-service

server.port=4001
grpc.server.port=9001

#server port is where the billing service REST API req goes
#grpc server port is where billingservice grpc server handles request